#!/usr/bin/env bash
# Display information about subdomains

function audit_subdomain {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        result=$(dig +short "$sub.$domain" | head -n1)
        
        if [ -z "$result" ]; then
            echo "The subdomain $sub does not exist for domain $domain"
        else
            record_type=$(dig "$sub.$domain" | awk '/IN/ {print $4}')
            destination=$(dig "$sub.$domain" | awk '/IN/ {print $5}')
            echo "The subdomain $sub is a $record_type record and points to $destination"
        fi
    done
}

audit_subdomain "$1" "$2"

